--liquibase formatted sql

--changeset gemini-cli:01-create-users-table
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);
--rollback DROP TABLE users;
