--liquibase formatted sql

-- Offers module: catalog tables (brand, category, product, offer, the attribute "bag", offer images).

--changeset rpikul:02-01-create-brand
CREATE TABLE brand (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)  NOT NULL,
    slug        VARCHAR(255)  NOT NULL UNIQUE,
    logo_url    VARCHAR(1024),
    description TEXT,
    is_active   BOOLEAN       NOT NULL DEFAULT TRUE
);
--rollback DROP TABLE brand;

--changeset rpikul:02-02-create-category
CREATE TABLE category (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  BIGINT       REFERENCES category(id),
    name       VARCHAR(255) NOT NULL,
    slug       VARCHAR(255) NOT NULL UNIQUE,
    sort_order INT          NOT NULL DEFAULT 0,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE
);
CREATE INDEX ix_category_parent ON category(parent_id);
--rollback DROP TABLE category;

--changeset rpikul:02-03-create-product
CREATE TABLE product (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug           VARCHAR(255) NOT NULL UNIQUE,
    name           VARCHAR(255) NOT NULL,
    description    TEXT,
    category_id    BIGINT       NOT NULL REFERENCES category(id),
    brand_id       BIGINT       REFERENCES brand(id),
    search_text    TEXT,
    main_image_url VARCHAR(1024),
    status         VARCHAR(32)  NOT NULL,
    -- Denormalized {root,…,leaf} chain; SQL-managed, not JPA-mapped.
    category_path  BIGINT[],
    -- Display-only blob; SQL-managed, not JPA-mapped.
    specs          JSONB,
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL
);
CREATE INDEX ix_product_category ON product(category_id);
CREATE INDEX ix_product_brand ON product(brand_id);
--rollback DROP TABLE product;

--changeset rpikul:02-04-create-offer
CREATE TABLE offer (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       BIGINT        NOT NULL REFERENCES product(id),
    sku              VARCHAR(255)  NOT NULL UNIQUE,
    price            NUMERIC(12,2) NOT NULL,
    price_currency   VARCHAR(3)    NOT NULL DEFAULT 'PLN',
    compare_at_price NUMERIC(12,2),
    stock            INT           NOT NULL DEFAULT 0,
    status           VARCHAR(32)   NOT NULL,
    created_at       TIMESTAMPTZ   NOT NULL,
    updated_at       TIMESTAMPTZ   NOT NULL
);
CREATE INDEX ix_offer_product ON offer(product_id);
--rollback DROP TABLE offer;

--changeset rpikul:02-05-create-attribute
CREATE TABLE attribute (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(64)  NOT NULL UNIQUE,
    name            VARCHAR(255) NOT NULL,
    data_type       VARCHAR(16)  NOT NULL,
    unit            VARCHAR(32),
    is_variant_axis BOOLEAN      NOT NULL DEFAULT FALSE
);
--rollback DROP TABLE attribute;

--changeset rpikul:02-06-create-category-attribute
CREATE TABLE category_attribute (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id  BIGINT  NOT NULL REFERENCES category(id),
    attribute_id BIGINT  NOT NULL REFERENCES attribute(id),
    filterable   BOOLEAN NOT NULL DEFAULT TRUE,
    required     BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order   INT     NOT NULL DEFAULT 0,
    CONSTRAINT uq_category_attribute UNIQUE (category_id, attribute_id)
);
--rollback DROP TABLE category_attribute;

--changeset rpikul:02-07-create-offer-attribute-value
CREATE TABLE offer_attribute_value (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id     BIGINT NOT NULL REFERENCES offer(id),
    attribute_id BIGINT NOT NULL REFERENCES attribute(id),
    text_value   VARCHAR(512),
    num_value    NUMERIC(18,4),
    bool_value   BOOLEAN,
    CONSTRAINT uq_offer_attribute_value UNIQUE (offer_id, attribute_id)
);
-- Facet GROUP BY + equality/range filter support (the "bag" lookups).
CREATE INDEX ix_oav_attr_text ON offer_attribute_value(attribute_id, text_value);
CREATE INDEX ix_oav_attr_num ON offer_attribute_value(attribute_id, num_value);
--rollback DROP TABLE offer_attribute_value;

--changeset rpikul:02-08-create-offer-image
CREATE TABLE offer_image (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id   BIGINT        NOT NULL REFERENCES offer(id),
    url        VARCHAR(1024) NOT NULL,
    alt        VARCHAR(255),
    sort_order INT           NOT NULL DEFAULT 0
);
CREATE INDEX ix_offer_image_offer ON offer_image(offer_id);
--rollback DROP TABLE offer_image;

-- Postgres-specific search/navigation indexes: pg_trgm ILIKE on search_text, GIN on category_path.
--changeset rpikul:02-09-search-indexes
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX ix_product_search_text_trgm ON product USING gin (search_text gin_trgm_ops);
CREATE INDEX ix_product_category_path ON product USING gin (category_path);
--rollback DROP INDEX IF EXISTS ix_product_category_path;
--rollback DROP INDEX IF EXISTS ix_product_search_text_trgm;
